### ISSUE TITLE
Changes to support `openfe` 1.0, `gufe` 1.0

### ISSUE THREAD

**Issue by dotsdl** [choderalab/feflow#31]
There are changes in `openfe` and `gufe` for their respective 1.0 releases, in particular in `Settings`. These should be addressed in advance of a new `feflow` release.

@richardjgowers can give more insights into what has changed in these packages.

**Comment by IAlibay** [comment]
From an initial look, this is going to require a resonably large amount of changes in the NEQ protocol, at least the way mappings are handled needs changing.

I've taken an initial stab in #33 - happy to hand over as necessary @ijpulidos

**Comment by ijpulidos** [comment]
In order to keep things more modular and easier to understand I'm going to enumerate the things that will be needed for us to support 1.0 releases of `gufe` and `openfe`.

TODO:
- [ ] Fix IntegratorSettings
  - [ ] Make a new integrator settings class for NEQ integrator
- [ ] Fix solvation settings
  - [ ] _should_ be just an import replacement
- [ ] Deal with mapping changes
  - [ ] SIngle mapping validation
  - [ ] Make sure everything is now a list rather than a dictionary
  - [ ] Remove dependency on "ligand" dictionary entry in mapping

**Comment by dotsdl** [comment]
Is this one now complete @ijpulidos?

**Comment by ijpulidos** [comment]
Yes, #38 should have taken care of this, closing!
